apiVersion: v1
kind: Service
metadata:
  name: poi-node
  namespace: poi-network
  labels:
    app.kubernetes.io/name: poi-network
    app.kubernetes.io/component: node
    app.kubernetes.io/part-of: decentralized-proof-of-contact-network
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: api
      port: 3000
      targetPort: api
      protocol: TCP
    - name: p2p
      port: 9090
      targetPort: p2p
      protocol: TCP
    - name: metrics
      port: 9091
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: poi-network
    app.kubernetes.io/component: node
